package repositories

import (
	_ "embed"
)

var (
	//go:embed region-queries/create.sql
	createRegion string
	//go:embed region-queries/find-by-id.sql
	findRegionById string
	//go:embed region-queries/find-by-name.sql
	findRegionByName string
	//go:embed city-queries/create.sql
	createCity string
	//go:embed city-queries/find-by-id.sql
	findCityById string
	//go:embed city-queries/find-by-name.sql
	findCityByName string
	//go:embed address-queries/create.sql
	createAddress string
	//go:embed address-queries/find-by-id.sql
	findAddress string
	//go:embed bank-queries/create.sql
	createBank string
	//go:embed bank-queries/find-by-id.sql
	findBankById string
	//go:embed bank-queries/find-by-name.sql
	findBankByName string
	//go:embed brand-queries/create.sql
	createBrand string
	//go:embed brand-queries/find-by-id.sql
	findBrandById string
	//go:embed brand-queries/find-by-name.sql
	findBrandByName string
	//go:embed currency-queries/create.sql
	createCurrency string
	//go:embed currency-queries/find-by-id.sql
	findCurrencyById string
	//go:embed currency-queries/find-by-name.sql
	findCurrencyByName string
	//go:embed delivery-service-queries/create.sql
	createDeliveryService string
	//go:embed delivery-service-queries/find-by-id.sql
	findDeliveryServiceById string
	//go:embed delivery-service-queries/find-by-name.sql
	findDeliveryServiceByName string
	//go:embed item-status-queries/create.sql
	createItemStatus string
	//go:embed item-status-queries/find-by-id.sql
	findItemStatusById string
	//go:embed item-status-queries/find-by-value.sql
	findItemStatusByValue string
	//go:embed locale-queries/create.sql
	createLocale string
	//go:embed locale-queries/find-by-id.sql
	findLocaleById string
	//go:embed locale-queries/find-by-name.sql
	findLocaleByName string
	//go:embed provider-queries/create.sql
	createProvider string
	//go:embed provider-queries/find-by-id.sql
	findProviderById string
	//go:embed provider-queries/find-by-name.sql
	findProviderByName string
	//go:embed delivery-queries/create.sql
	createDelivery string
	//go:embed delivery-queries/find-by-id.sql
	findDeliveryById string
	//go:embed delivery-queries/find-by-customer-and-address.sql
	findDeliveryByCustomerAndAddress string
	//go:embed customer-queries/create.sql
	createCustomer string
	//go:embed customer-queries/find-by-id.sql
	findCustomerById string
	//go:embed customer-queries/find-by-phone.sql
	findCustomerByPhone string
	//go:embed item-queries/create.sql
	createItem string
	//go:embed item-queries/find-by-id.sql
	findItemById string
	//go:embed item-queries/list-by-ids.sql
	listItemByIds string
	//go:embed payment-queries/create.sql
	createPayment string
	//go:embed payment-queries/find-by-id.sql
	findPaymentById string
	//go:embed orderRepository-queries/create-orderRepository.sql
	createOrder string
	//go:embed orderRepository-queries/create-orderRepository-item.sql
	createOrderItem string
	//go:embed orderRepository-queries/get-orderRepository-by-id.sql
	getOrderById string
	//go:embed orderRepository-queries/get-orderRepository-items-by-orderRepository-id.sql
	getOrderItemsByOrderId string
	//go:embed orderRepository-queries/get-orders-by-limit.sql
	getOrdersByLimit string
)
