package repositories

import (
	_ "embed"
)

var (
	//go:embed region-queries/create.sql
	createRegion string
	//go:embed city-queries/create.sql
	createCity string
	//go:embed address-queries/create.sql
	createAddress string
	//go:embed bank-queries/create.sql
	createBank string
	//go:embed brand-queries/create.sql
	createBrand string
	//go:embed brand-queries/find-by-id.sql
	findBrandById string
	//go:embed currency-queries/create.sql
	createCurrency string
	//go:embed delivery-service-queries/create.sql
	createDeliveryService string
	//go:embed item-status-queries/create.sql
	createItemStatus string
	//go:embed item-status-queries/find-by-id.sql
	findItemStatusById string
	//go:embed locale-queries/create.sql
	createLocale string
	//go:embed provider-queries/create.sql
	createProvider string
	//go:embed delivery-queries/create.sql
	createDelivery string
	//go:embed customer-queries/create.sql
	createCustomer string
	//go:embed item-queries/create.sql
	createItem string
	//go:embed item-queries/list-by-ids.sql
	listItemByIds string
	//go:embed payment-queries/create.sql
	createPayment string
	//go:embed order-queries/create-order.sql
	createOrder string
	//go:embed order-queries/create-order-item.sql
	createOrderItem string
	//go:embed order-queries/get-order-by-id.sql
	getOrderById string
	//go:embed order-queries/get-order-items-by-order-id.sql
	getOrderItemsByOrderId string
	//go:embed order-queries/get-orders-by-limit.sql
	getOrdersByLimit string
)
